# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - icpna-landing-backend-4521

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: mcr.microsoft.com/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_62E50BA1E76A427A9F5A8E7A2E2CC2C7 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_DB39B00FBF274112897E7EB66C286EF1 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mcr.microsoft.com/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_62E50BA1E76A427A9F5A8E7A2E2CC2C7 }}/appsvc/staticsite:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02B0FC2467F44EBF977B83E2F47BE734 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C64323C125A146239CC0BFEFC27C883A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_374AF107F15C4685B8801D6763EB3F65 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'icpna-landing-backend-4521'
          slot-name: 'Production'
          images: 'mcr.microsoft.com/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_62E50BA1E76A427A9F5A8E7A2E2CC2C7 }}/appsvc/staticsite:${{ github.sha }}'
          